### ISSUE TITLE
Does not compile with gfortran

### ISSUE THREAD

**Issue by cbyrohl** [jacobwilliams/fortran-search-and-sort#1]
Hi there,

gfortran compilation fails with "gfortran -c -O2 -std=f2008" as given in build.sh. First error:

```
src/sorting_module.f90:31:54:

         pure elemental subroutine assign_equal_func(v1,v2)
                                                      1
Error: INTENT(OUT) argument ‘v1’ of pure procedure ‘assign_equal_func’ at (1) may not be polymorphic
item_routines.inc:16:46
```

followed by a lot of

```
sort_descending.inc:54.48:
    Included at real64_routines.inc:33:
    Included at src/sorting_module.f90:127:

        call swap(vec(ilow),vec((ilow+ihigh)/2))
                                                1
Error: There is no specific subroutine for the generic 'swap' at (1)
```

Note that I get the latter error as well with the default intel compiler "ifort -c -O2 -warn -stand f15 -traceback"

Best,
Chris

**Comment by jacobwilliams** [comment]
Yes, there is a note in the code about this. I think this is a Fortran 2015 change or clarification. I can update the code to be F15 compliant.

**Comment by cbyrohl** [comment]
I was unaware of that. While I write my own algorithms based on pseudo code, I think it would be beneficial to others for the code to be updated. Thank you for your help.

Best,
